

import { Inter } from "next/font/google";
import "./globals.css";
import App from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

import Provider from "@/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children , session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
      <App/>
      {children}
      <Footer/>
      </Provider>
      </body>
    </html>
  );
}
